#!/bin/sh
nwmc set vgaps 8
nwmc set hgaps 8
nwmc set bord_size 4

nwmc set bord_foc_col ffc4a7e7L
nwmc set bord_nor_col ff26233aL

nwmc bind "super q" exitwm "0"
nwmc bind "super a" spawn  "st"
nwmc bind "super r" spawn  "rofi -normal-window -show drun"
