#!/bin/sh
nwmc vertical_gaps 20
nwmc horizontal_gaps 20
nwmc border_size 4
nwmc resize_amount 2
nwmc minimum_size 50
nwmc number_of_desktops 2

nwmc focused_border_color ffc4a7e7L
nwmc normal_border_color ff26233aL

# CHECK IF THESE STRIGS GET ALLOCATED OR COPIED OR JUST USED IN CONFIG.C
# they should be allocated and memcopied?

# to add swapping

mod="alt"

nwmc bind clear

nwmc bind "Print" spawn "/home/ethan/.config/scripts/scrot.sh 0"
nwmc bind "ctrl Print" spawn "/home/ethan/.config/scripts/scrot.sh 1"

nwmc bind "XF86AudioRaiseVolume" spawn "amixer set Master 5%+"
nwmc bind "XF86AudioLowerVolume" spawn "amixer set Master 5%-"
nwmc bind "XF86AudioMute" spawn "amixer set Master toggle"

nwmc bind "$mod shift q" exit 0
nwmc bind "$mod f" float 0
nwmc bind "$mod space" focus_toggle 0

nwmc bind "$mod s" spawn "st"
nwmc bind "$mod r" spawn "/home/ethan/neowm/nwm.conf"
nwmc bind "$mod q" kill_window 0
nwmc bind "$mod a" spawn "rofi -show drun"

nwmc bind "$mod k" focus_switch up
nwmc bind "$mod j" focus_switch down
nwmc bind "$mod h" focus_switch left
nwmc bind "$mod l" focus_switch right

nwmc bind "$mod shift k" resize_window up
nwmc bind "$mod shift j" resize_window down
nwmc bind "$mod shift h" resize_window left
nwmc bind "$mod shift l" resize_window right

nwmc bind "$mod 1" switch_desktop 0
nwmc bind "$mod 2" switch_desktop 1
