#!/bin/sh

# Settings:
nwmc vertical_gaps 40
nwmc horizontal_gaps 40
nwmc border_size 4
nwmc resize_amount 2
nwmc move_amount 20
nwmc minimum_size 50

# should prob have the same number of desktops as names...
nwmc number_of_desktops 5
#nwmc desktop_names "一 二 三 四 五 六 七 八 九 十"
nwmc desktop_names "一 二 三 四 五"
#nwmc desktop_names "one two thr fou fiv"

nwmc refresh_rate 180
nwmc split_ratio 50
#borderless_monocle
#bgapless_monocle
#single_monocle

nwmc focused_border_color ff005577
nwmc normal_border_color ff444444

# Binds:
mod="super"
nwmc bind clear

# WM:
nwmc bind "$mod shift q" exit 0
nwmc bind "$mod r" spawn "/home/ethan/neowm/nwm.conf"

# Windows:
nwmc bind "$mod f" float_toggle 0
nwmc bind "$mod space" focus_toggle 0
nwmc bind "$mod q" kill_window 0

# Apps:
nwmc bind "$mod a" spawn "rofi -show drun"
nwmc bind "$mod enter" spawn "st"
nwmc bind "$mod b" spawn "chromium"

# Utils:
nwmc bind "Print" spawn "/home/ethan/.config/scripts/scrot.sh 0"
nwmc bind "ctrl Print" spawn "/home/ethan/.config/scripts/scrot.sh 1"
nwmc bind "XF86AudioRaiseVolume" spawn "amixer set Master 5%+"
nwmc bind "XF86AudioLowerVolume" spawn "amixer set Master 5%-"
nwmc bind "XF86AudioMute" spawn "amixer set Master toggle"

# Mouse:
nwmc bind "$mod Button1" drag_move_window 0
nwmc bind "$mod Button3" drag_resize_window 0

# Tilled Management:
nwmc bind "$mod k" focus_window up
nwmc bind "$mod j" focus_window down
nwmc bind "$mod h" focus_window left
nwmc bind "$mod l" focus_window right

nwmc bind "$mod control k" swap_window up
nwmc bind "$mod control j" swap_window down
nwmc bind "$mod control h" swap_window left
nwmc bind "$mod control l" swap_window right

# Floating Management:
nwmc bind "$mod k" move_window up
nwmc bind "$mod j" move_window down
nwmc bind "$mod h" move_window left
nwmc bind "$mod l" move_window right

nwmc bind "$mod shift k" resize_window up
nwmc bind "$mod shift j" resize_window down
nwmc bind "$mod shift h" resize_window left
nwmc bind "$mod shift l" resize_window right

# Desktops:
nwmc bind "$mod 1" focus_desktop 0
nwmc bind "$mod 2" focus_desktop 1
nwmc bind "$mod 3" focus_desktop 2
nwmc bind "$mod 4" focus_desktop 3
nwmc bind "$mod 5" focus_desktop 4
nwmc bind "$mod 6" focus_desktop 5
nwmc bind "$mod 7" focus_desktop 6
nwmc bind "$mod 8" focus_desktop 7
nwmc bind "$mod 9" focus_desktop 8
nwmc bind "$mod 0" focus_desktop 9

nwmc bind "$mod shift 1" move_desktop 0
nwmc bind "$mod shift 2" move_desktop 1
nwmc bind "$mod shift 3" move_desktop 2
nwmc bind "$mod shift 4" move_desktop 3
nwmc bind "$mod shift 5" move_desktop 4
nwmc bind "$mod shift 6" move_desktop 5
nwmc bind "$mod shift 7" move_desktop 6
nwmc bind "$mod shift 8" move_desktop 7
nwmc bind "$mod shift 9" move_desktop 8
nwmc bind "$mod shift 0" move_desktop 9
